-- Generated from the canonical Everkind SQLite schema.

-- Application tables are private to the server: no Data API grants or RLS policies are created.

BEGIN;

CREATE OR REPLACE FUNCTION public.datetime(value text, VARIADIC modifiers text[])
RETURNS text
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    result_value timestamp without time zone;
    modifier text;
BEGIN
    IF lower(value) = 'now' THEN
        result_value := CURRENT_TIMESTAMP AT TIME ZONE 'UTC';
    ELSIF value ~ '(Z|[+-][0-9]{2}:[0-9]{2})$' THEN
        result_value := value::timestamptz AT TIME ZONE 'UTC';
    ELSE
        result_value := value::timestamp;
    END IF;

    FOREACH modifier IN ARRAY modifiers LOOP
        result_value := result_value + modifier::interval;
    END LOOP;

    RETURN to_char(result_value, 'YYYY-MM-DD HH24:MI:SS');
END;
$$;

CREATE OR REPLACE FUNCTION public.date(value text, VARIADIC modifiers text[])
RETURNS text
LANGUAGE sql
STABLE
AS $$
    SELECT split_part(public.datetime(value, VARIADIC modifiers), ' ', 1);
$$;

CREATE OR REPLACE FUNCTION public.datetime(value text)
RETURNS text
LANGUAGE sql
STABLE
AS $$
    SELECT public.datetime(value, VARIADIC ARRAY[]::text[]);
$$;

CREATE OR REPLACE FUNCTION public.date(value text)
RETURNS text
LANGUAGE sql
STABLE
AS $$
    SELECT public.date(value, VARIADIC ARRAY[]::text[]);
$$;

CREATE TABLE "admin_users" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" text,
    "password_hash" text,
    "role" text DEFAULT 'super_admin',
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "name" text,
    "department" text,
    "phone" text,
    "email_normalized" text,
    "phone_normalized" text,
    "email_verified" integer NOT NULL DEFAULT 0,
    "phone_verified" integer NOT NULL DEFAULT 0,
    "mfa_enabled" integer NOT NULL DEFAULT 0,
    "mfa_preferred_method" text,
    "totp_secret_encrypted" text,
    "totp_verified_at" text,
    "mfa_reset_required" integer NOT NULL DEFAULT 0,
    "mfa_version" integer NOT NULL DEFAULT 1,
    "is_active" integer NOT NULL DEFAULT 1,
    "last_login" text,
    "last_login_ip" text,
    "auth_version" integer NOT NULL DEFAULT 1,
    "updated_at" text,
    UNIQUE ("username")
);

CREATE TABLE "app_status" (
    "id" integer PRIMARY KEY CHECK (id = 1),
    "status" text NOT NULL DEFAULT 'healthy',
    "updated_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "application_timeline" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "application_id" integer NOT NULL,
    "stage" text NOT NULL,
    "title" text NOT NULL,
    "notes" text,
    "actor_type" text,
    "actor_identifier" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "applications" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "email" text,
    "phone" text,
    "role" text,
    "availability" text,
    "status" text DEFAULT 'new',
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "first_name" text,
    "surname" text,
    "email_normalized" text,
    "phone_normalized" text,
    "application_ref" text,
    "reviewed_at" text,
    "reviewed_by" text,
    "shortlisted_at" text,
    "interview_scheduled_at" text,
    "interview_completed_at" text,
    "offer_sent_at" text,
    "offer_accepted_at" text,
    "pre_employment_checks_at" text,
    "induction_started_at" text,
    "approved_employee_at" text,
    "active_staff_at" text,
    "rejected_at" text,
    "archived_at" text,
    "last_stage_changed_at" text,
    "last_stage_changed_by" text
);

CREATE TABLE "appointments" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "patient_id" integer,
    "staff_id" integer,
    "title" text,
    "start" text,
    "end" text,
    "notes" text,
    "status" text DEFAULT 'Scheduled',
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "client" text,
    "date" text,
    "time" text,
    "type" text
);

CREATE TABLE "audit_events" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "actor_type" text NOT NULL,
    "actor_identifier" text,
    "action" text NOT NULL,
    "target_type" text,
    "target_identifier" text,
    "outcome" text NOT NULL,
    "reason" text,
    "ip_address" text,
    "user_agent" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "actor_role" text,
    "metadata" text
);

CREATE TABLE "care_notes" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "patient_id" integer,
    "author" text,
    "note" text,
    "severity" text DEFAULT 'Normal',
    "retention_expires_at" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "care_reviews" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "patient_id" integer NOT NULL,
    "review_type" text NOT NULL DEFAULT 'care',
    "reviewer_staff_id" integer,
    "due_date" text NOT NULL,
    "completed_at" text,
    "status" text NOT NULL DEFAULT 'upcoming',
    "notes" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "updated_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "client_accounts" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_name" text NOT NULL,
    "trading_name" text,
    "organization_type" text NOT NULL,
    "registration_number" text,
    "hiqa_registration_number" text,
    "hse_contract_number" text,
    "vat_number" text,
    "website" text,
    "contact_first_name" text NOT NULL,
    "contact_last_name" text NOT NULL,
    "contact_job_title" text,
    "email" text NOT NULL,
    "mobile_number" text NOT NULL,
    "office_telephone" text,
    "address_line_1" text NOT NULL,
    "address_line_2" text,
    "town" text NOT NULL,
    "county" text NOT NULL,
    "eircode" text,
    "gps_latitude" double precision,
    "gps_longitude" double precision,
    "service_requirements" text,
    "number_of_beds" text,
    "number_of_residents" text,
    "number_of_units" text,
    "existing_staff_numbers" text,
    "current_staffing_provider" text,
    "preferred_shift_types" text,
    "gdpr_agreement" integer DEFAULT 0,
    "privacy_agreement" integer DEFAULT 0,
    "terms_agreement" integer DEFAULT 0,
    "hiqa_compliance_agreement" integer DEFAULT 0,
    "authorised_representative" integer DEFAULT 0,
    "status" text DEFAULT 'pending',
    "password_hash" text,
    "portal_login_enabled" integer DEFAULT 0,
    "portal_login_suspended" integer DEFAULT 0,
    "portal_login_deactivated" integer DEFAULT 0,
    "approved_at" text,
    "approved_by" text,
    "review_notes" text,
    "assigned_account_manager" text,
    "favourite_staff_ids" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "updated_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "facility_id" text,
    "onboarded" integer DEFAULT 0,
    "force_password_reset" integer DEFAULT 0,
    UNIQUE ("email")
);

CREATE TABLE "client_notifications" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "client_account_id" integer NOT NULL,
    "title" text NOT NULL,
    "body" text NOT NULL,
    "type" text DEFAULT 'info',
    "link_url" text,
    "is_read" integer DEFAULT 0,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "client_password_resets" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "client_account_id" integer NOT NULL,
    "code_hash" text NOT NULL,
    "expires_at" text NOT NULL,
    "used_at" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "client_service_requests" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "client_account_id" integer NOT NULL,
    "staff_required" text NOT NULL,
    "quantity_required" integer DEFAULT 1,
    "shift_type" text NOT NULL,
    "shift_date" text NOT NULL,
    "start_time" text NOT NULL,
    "end_time" text NOT NULL,
    "ward_unit" text,
    "resident_identifier" text,
    "room_number" text,
    "resident_unit" text,
    "required_skills" text,
    "notes" text,
    "priority" text DEFAULT 'Routine',
    "status" text DEFAULT 'open',
    "assigned_staff_id" integer,
    "published_open_shift_id" integer,
    "scheduled_shift_id" integer,
    "completed_at" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "updated_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "facility_name" text,
    "facility_type" text,
    "facility_address" text,
    "facility_county" text,
    "facility_eircode" text,
    "facility_gps_latitude" double precision,
    "facility_gps_longitude" double precision,
    "contact_person" text,
    "contact_position" text,
    "contact_phone" text,
    "contact_email" text,
    "emergency_contact" text,
    "break_duration_minutes" integer DEFAULT 0,
    "total_paid_hours" double precision,
    "recurring_pattern" text,
    "multiple_dates" text,
    "weekly_repeat_day" text,
    "monthly_repeat_date" integer,
    "hourly_rate" double precision,
    "required_training" text,
    "minimum_experience_years" double precision,
    "healthcare_setting_required" text,
    "driving_licence_required" integer DEFAULT 0,
    "own_vehicle_required" integer DEFAULT 0,
    "english_language_level" text,
    "additional_certifications" text,
    "uniform_required" integer DEFAULT 0,
    "parking_available" integer DEFAULT 0,
    "smoking_household" integer DEFAULT 0,
    "pets_on_premises" integer DEFAULT 0,
    "special_instructions" text,
    "language_requirement" text,
    "travel_radius_km" double precision,
    "accepted_by_staff_at" text,
    "approved_at" text
);

CREATE TABLE "mfa_challenges" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "account_type" text NOT NULL,
    "account_id" integer NOT NULL,
    "purpose" text NOT NULL,
    "method" text NOT NULL,
    "nonce" text NOT NULL,
    "code_hash" text NOT NULL,
    "attempts_remaining" integer NOT NULL DEFAULT 5,
    "expires_at" text NOT NULL,
    "resend_after" text NOT NULL,
    "consumed_at" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "mfa_recovery_codes" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "account_type" text NOT NULL,
    "account_id" integer NOT NULL,
    "code_hash" text NOT NULL,
    "used_at" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "password_history" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "account_type" text NOT NULL,
    "account_id" integer NOT NULL,
    "password_hash" text NOT NULL,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "patient_assignments" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "patient_id" integer NOT NULL,
    "staff_id" integer NOT NULL,
    "assignment_role" text NOT NULL,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "patient_documents" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "patient_id" integer NOT NULL,
    "title" text NOT NULL,
    "category" text NOT NULL,
    "file_name" text NOT NULL,
    "mime_type" text,
    "data_url" text NOT NULL,
    "is_staff_visible" integer DEFAULT 1,
    "uploaded_by" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "patients" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "first_name" text,
    "last_name" text,
    "date_of_birth" text,
    "gender" text,
    "address" text,
    "phone" text,
    "email" text,
    "emergency_contact" text,
    "care_level" text,
    "status" text DEFAULT 'Active',
    "risk_level" text DEFAULT 'Low',
    "latitude" double precision,
    "longitude" double precision,
    "geofence_radius_meters" integer DEFAULT 80,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "age" integer,
    "condition" text,
    "carePlan" text,
    "nextVisit" text,
    "name" text,
    "legal_basis" text DEFAULT 'care_contract',
    "consent_status" text DEFAULT 'pending',
    "consent_recorded_at" text,
    "consent_recorded_by" text,
    "data_retention_until" text,
    "is_archived" integer DEFAULT 0,
    "archived_at" text,
    "home_care_client_id" text,
    "eircode" text,
    "photo_url" text,
    "emergency_contact_name" text,
    "emergency_contact_relationship" text,
    "emergency_contact_phone" text,
    "preferred_name" text,
    "marital_status" text,
    "nationality" text,
    "pps_number" text,
    "primary_language" text,
    "interpreter_required" integer DEFAULT 0,
    "alternative_phone" text,
    "county" text,
    "care_needs_personal_care" text,
    "care_needs_mobility" text,
    "care_needs_clinical_tasks" text,
    "care_needs_medical_conditions" text,
    "care_needs_daily_living" text,
    "care_needs_risks" text,
    "care_needs_communication" text,
    "care_needs_lifestyle" text,
    "care_needs_equipment" text,
    "care_needs_service_types" text,
    "diagnoses" text,
    "allergies" text,
    "current_medication" text,
    "medication_schedule" text,
    "gp_name" text,
    "gp_phone" text,
    "consultant_name" text,
    "hospital_name" text,
    "pharmacy_name" text,
    "vaccination_status" text,
    "dnar_status" text,
    "falls_risk_level" text,
    "infection_risks" text,
    "emergency_contact_alt_phone" text,
    "emergency_contact_email" text,
    "emergency_contact_address" text,
    "key_safe_code" text,
    "door_code" text,
    "alarm_code" text,
    "parking_instructions" text,
    "pets" text,
    "lift_available" integer DEFAULT 0,
    "stairs" text,
    "access_notes" text,
    "care_plan_daily_routine" text,
    "care_plan_preferences" text,
    "care_plan_likes" text,
    "care_plan_dislikes" text,
    "care_plan_communication" text,
    "care_plan_diet" text,
    "care_plan_fluids" text,
    "care_plan_behaviour_support" text,
    "care_plan_risk_information" text,
    "care_plan_goals" text,
    "shift_instructions" text,
    "preferred_days" text,
    "preferred_times" text,
    "visit_duration" text,
    "custom_visit_duration" text,
    "visit_frequency" text,
    "custom_visit_frequency" text,
    "preferred_staff_gender" text,
    "internal_notes" text,
    "updated_at" text
);

CREATE TABLE "payroll_records" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "staff_id" integer NOT NULL,
    "period_start" text NOT NULL,
    "period_end" text NOT NULL,
    "total_hours" double precision DEFAULT 0,
    "gross_pay" double precision DEFAULT 0,
    "net_pay" double precision DEFAULT 0,
    "mileage_km" double precision DEFAULT 0,
    "mileage_payment" double precision DEFAULT 0,
    "status" text DEFAULT 'draft',
    "approved_by" text,
    "approved_at" text,
    "paid_at" text,
    "payment_date" text,
    "notes" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "updated_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "snapshot_json" text,
    UNIQUE ("staff_id", "period_start", "period_end")
);

CREATE TABLE "payslip_email_log" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "payslip_id" integer NOT NULL,
    "staff_id" integer NOT NULL,
    "email_address" text,
    "subject" text,
    "status" text,
    "error_message" text,
    "sent_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "payslips" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "staff_id" integer NOT NULL,
    "payroll_record_id" integer,
    "period_start" text NOT NULL,
    "period_end" text NOT NULL,
    "gross_pay" double precision DEFAULT 0,
    "net_pay" double precision DEFAULT 0,
    "file_path" text,
    "payment_date" text,
    "email_status" text DEFAULT 'not_scheduled',
    "email_scheduled_at" text,
    "email_sent_at" text,
    "generated_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "generated_by" text,
    "payslip_ref" text,
    UNIQUE ("payslip_ref")
);

CREATE TABLE "permissions" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "permission_key" text NOT NULL,
    "module_key" text NOT NULL,
    "action" text NOT NULL,
    "description" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE ("permission_key")
);

CREATE TABLE "role_permissions" (
    "role_id" integer NOT NULL,
    "permission_id" integer NOT NULL,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    PRIMARY KEY ("role_id", "permission_id")
);

CREATE TABLE "roles" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_key" text NOT NULL,
    "label" text NOT NULL,
    "description" text,
    "is_system" integer NOT NULL DEFAULT 0,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "updated_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE ("role_key")
);

CREATE TABLE "shift_attachments" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "shift_id" integer NOT NULL,
    "title" text NOT NULL,
    "category" text NOT NULL,
    "file_name" text,
    "download_text" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "staff" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "first_name" text,
    "last_name" text,
    "role" text,
    "email" text,
    "phone" text,
    "status" text DEFAULT 'Active',
    "password_hash" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "name" text,
    "shift" text,
    "email_normalized" text,
    "phone_normalized" text,
    "email_verified" integer NOT NULL DEFAULT 0,
    "phone_verified" integer NOT NULL DEFAULT 0,
    "mfa_enabled" integer NOT NULL DEFAULT 0,
    "mfa_preferred_method" text,
    "totp_secret_encrypted" text,
    "totp_verified_at" text,
    "mfa_reset_required" integer NOT NULL DEFAULT 0,
    "mfa_version" integer NOT NULL DEFAULT 1,
    "updated_at" text,
    "mobile_number" text,
    "is_archived" integer NOT NULL DEFAULT 0,
    "address" text,
    "emergency_contact" text,
    "availability" text,
    "manager_name" text,
    "start_date" text,
    "nationality" text,
    "languages" text,
    "experience_years" text,
    "employee_number" text,
    "preferred_name" text,
    "profile_photo" text,
    "date_of_birth" text,
    "gender" text,
    "pps_number" text,
    "driving_licence_number" text,
    "driving_licence_categories" text,
    "own_vehicle" integer DEFAULT 0,
    "right_to_work" text,
    "visa_type" text,
    "visa_expiry_date" text,
    "passport_number" text,
    "passport_expiry_date" text,
    "alternative_phone" text,
    "home_address" text,
    "eircode" text,
    "county" text,
    "emergency_contact_name" text,
    "emergency_contact_relationship" text,
    "emergency_contact_phone" text,
    "emergency_contact_email" text,
    "employment_type" text,
    "service_types" text,
    "employment_status" text,
    "end_date" text,
    "hourly_rate" text,
    "payroll_number" text,
    "branch" text,
    "qqi_qualifications" text,
    "professional_registration" text,
    "other_qualifications" text,
    "skills_specialities" text,
    "mandatory_training" text,
    "additional_certifications" text,
    "availability_days" text,
    "shift_preferences" text,
    "weekend_availability" integer DEFAULT 0,
    "bank_holidays" integer DEFAULT 0,
    "max_weekly_hours" text,
    "preferred_working_area" text,
    "internal_notes" text,
    "staff_notes" text,
    "compliance_summary" text,
    "application_id" integer,
    "induction_checklist" text,
    "portal_login_enabled" integer DEFAULT 1,
    "portal_login_suspended" integer DEFAULT 0,
    "portal_login_deactivated" integer DEFAULT 0,
    "welcome_email_sent" integer DEFAULT 0,
    "training_records" text,
    "certification_records" text,
    "nmbi_number" text,
    "nmbi_expiry_date" text,
    "garda_vetting_status" text,
    "garda_vetting_expiry_date" text,
    "force_password_reset" integer DEFAULT 0,
    "app_lock_enabled" integer DEFAULT 0,
    "app_lock_method" text,
    "reminder_lead_minutes" integer DEFAULT 60,
    "notify_shift_reminders" integer DEFAULT 1,
    "notify_new_shift" integer DEFAULT 1,
    "notify_open_shift" integer DEFAULT 1,
    "notify_announcements" integer DEFAULT 1,
    "notify_training_reminders" integer DEFAULT 1,
    "notify_compliance_alerts" integer DEFAULT 1,
    "notify_schedule_changes" integer DEFAULT 1,
    UNIQUE ("email")
);

CREATE TABLE "staff_documents" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "staff_id" integer,
    "title" text NOT NULL,
    "category" text NOT NULL,
    "file_name" text,
    "download_text" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "staff_messages" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "staff_id" integer NOT NULL,
    "sender_type" text NOT NULL,
    "sender_name" text NOT NULL,
    "subject" text,
    "body" text NOT NULL,
    "is_read" integer DEFAULT 0,
    "archived_at" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "staff_notifications" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "staff_id" integer NOT NULL,
    "title" text NOT NULL,
    "body" text NOT NULL,
    "type" text DEFAULT 'info',
    "link_url" text,
    "is_read" integer DEFAULT 0,
    "deleted_at" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "staff_password_resets" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "staff_id" integer NOT NULL,
    "code_hash" text NOT NULL,
    "expires_at" text NOT NULL,
    "used_at" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "staff_shift_reminders" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "shift_id" integer NOT NULL,
    "staff_id" integer NOT NULL,
    "reminder_type" text NOT NULL,
    "reminder_minutes" integer,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "staff_shift_visit_notes" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "shift_id" integer NOT NULL,
    "staff_id" integer NOT NULL,
    "note" text NOT NULL,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "staff_shifts" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "staff_id" integer,
    "patient_id" integer,
    "shift_date" text,
    "scheduled_start" text,
    "scheduled_end" text,
    "actual_clock_in" text,
    "actual_clock_out" text,
    "status" text DEFAULT 'scheduled',
    "clock_in_latitude" double precision,
    "clock_in_longitude" double precision,
    "clock_out_latitude" double precision,
    "clock_out_longitude" double precision,
    "clock_in_note" text,
    "clock_out_note" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "is_open" integer DEFAULT 0,
    "client_account_id" integer,
    "client_request_id" integer,
    "request_source" text,
    "external_client_label" text,
    "location_address" text,
    "location_town" text,
    "location_county" text,
    "location_eircode" text,
    "external_latitude" double precision,
    "external_longitude" double precision,
    "external_geofence_radius_meters" integer DEFAULT 100,
    "ward_unit" text,
    "service_division" text DEFAULT 'home-care',
    "shift_code" text,
    "facility_type" text,
    "role_required" text,
    "shift_requirements" text,
    "break_duration_minutes" integer DEFAULT 0,
    "quantity_required" integer DEFAULT 1,
    "contact_person" text,
    "mileage_km" double precision DEFAULT 0,
    "payroll_status" text DEFAULT 'draft',
    "notes" text,
    "service_type" text,
    "clock_in_accuracy" double precision,
    "clock_out_accuracy" double precision,
    "clock_in_device" text,
    "clock_out_device" text,
    "care_instructions" text,
    "pay_rate" double precision,
    "pay_rate_source" text
);

CREATE TABLE "staff_training" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "staff_id" integer NOT NULL,
    "title" text NOT NULL,
    "status" text DEFAULT 'completed',
    "completed_at" text,
    "expires_at" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "subject_requests" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "request_type" text NOT NULL,
    "patient_id" integer,
    "requested_by" text,
    "status" text NOT NULL,
    "details" text,
    "processed_at" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "system_settings" (
    "key" text PRIMARY KEY,
    "value" text,
    "updated_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "user_roles" (
    "admin_user_id" integer NOT NULL,
    "role_id" integer NOT NULL,
    "scope_type" text NOT NULL DEFAULT 'global',
    "scope_value" text NOT NULL DEFAULT '',
    "is_primary" integer NOT NULL DEFAULT 0,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    PRIMARY KEY ("admin_user_id", "role_id", "scope_type", "scope_value")
);

CREATE TABLE "website_announcements" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "headline" text NOT NULL,
    "message" text,
    "color" text DEFAULT 'emerald',
    "priority" text DEFAULT 'normal',
    "enabled" integer DEFAULT 1,
    "auto_scroll" integer DEFAULT 1,
    "start_date" text,
    "end_date" text,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "updated_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE "website_jobs" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" text NOT NULL,
    "location" text,
    "county" text,
    "employment_type" text,
    "salary" text,
    "description" text,
    "requirements" text,
    "benefits" text,
    "closing_date" text,
    "featured" integer DEFAULT 0,
    "urgent" integer DEFAULT 0,
    "published" integer DEFAULT 1,
    "archived" integer DEFAULT 0,
    "created_at" text DEFAULT (CURRENT_TIMESTAMP::text),
    "updated_at" text DEFAULT (CURRENT_TIMESTAMP::text)
);

ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_permission_id_permissions_id" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON DELETE CASCADE;

ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_role_id_roles_id" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE;

ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_role_id_roles_id" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE;

ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_admin_user_id_admin_users_id" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users" ("id") ON DELETE CASCADE;

CREATE INDEX idx_admin_users_active ON admin_users(is_active);

CREATE UNIQUE INDEX idx_admin_users_email_normalized_active ON admin_users(email_normalized) WHERE is_active = 1 AND email_normalized != '';

CREATE UNIQUE INDEX idx_admin_users_phone_normalized_active ON admin_users(phone_normalized) WHERE is_active = 1 AND phone_normalized != '';

CREATE UNIQUE INDEX idx_applications_email_normalized_unique
             ON applications(email_normalized)
             WHERE COALESCE(email_normalized, '') <> '';

CREATE UNIQUE INDEX idx_applications_phone_normalized_unique
             ON applications(phone_normalized)
             WHERE COALESCE(phone_normalized, '') <> '';

CREATE INDEX idx_audit_events_actor_role ON audit_events(actor_role);

CREATE INDEX idx_mfa_challenges_account ON mfa_challenges(account_type, account_id, purpose, created_at);

CREATE INDEX idx_mfa_recovery_account ON mfa_recovery_codes(account_type, account_id, used_at);

CREATE INDEX idx_password_history_account ON password_history(account_type, account_id, created_at);

CREATE UNIQUE INDEX idx_staff_email_normalized_active ON staff(email_normalized) WHERE COALESCE(is_archived, 0) = 0 AND email_normalized != '';

CREATE UNIQUE INDEX idx_staff_phone_normalized_active ON staff(phone_normalized) WHERE COALESCE(is_archived, 0) = 0 AND phone_normalized != '';

CREATE INDEX idx_user_roles_admin_user ON user_roles(admin_user_id);

ALTER TABLE "admin_users" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "admin_users" FROM anon, authenticated;

ALTER TABLE "app_status" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "app_status" FROM anon, authenticated;

ALTER TABLE "application_timeline" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "application_timeline" FROM anon, authenticated;

ALTER TABLE "applications" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "applications" FROM anon, authenticated;

ALTER TABLE "appointments" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "appointments" FROM anon, authenticated;

ALTER TABLE "audit_events" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "audit_events" FROM anon, authenticated;

ALTER TABLE "care_notes" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "care_notes" FROM anon, authenticated;

ALTER TABLE "care_reviews" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "care_reviews" FROM anon, authenticated;

ALTER TABLE "client_accounts" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "client_accounts" FROM anon, authenticated;

ALTER TABLE "client_notifications" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "client_notifications" FROM anon, authenticated;

ALTER TABLE "client_password_resets" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "client_password_resets" FROM anon, authenticated;

ALTER TABLE "client_service_requests" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "client_service_requests" FROM anon, authenticated;

ALTER TABLE "mfa_challenges" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "mfa_challenges" FROM anon, authenticated;

ALTER TABLE "mfa_recovery_codes" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "mfa_recovery_codes" FROM anon, authenticated;

ALTER TABLE "password_history" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "password_history" FROM anon, authenticated;

ALTER TABLE "patient_assignments" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "patient_assignments" FROM anon, authenticated;

ALTER TABLE "patient_documents" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "patient_documents" FROM anon, authenticated;

ALTER TABLE "patients" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "patients" FROM anon, authenticated;

ALTER TABLE "payroll_records" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "payroll_records" FROM anon, authenticated;

ALTER TABLE "payslip_email_log" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "payslip_email_log" FROM anon, authenticated;

ALTER TABLE "payslips" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "payslips" FROM anon, authenticated;

ALTER TABLE "permissions" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "permissions" FROM anon, authenticated;

ALTER TABLE "role_permissions" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "role_permissions" FROM anon, authenticated;

ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "roles" FROM anon, authenticated;

ALTER TABLE "shift_attachments" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "shift_attachments" FROM anon, authenticated;

ALTER TABLE "staff" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "staff" FROM anon, authenticated;

ALTER TABLE "staff_documents" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "staff_documents" FROM anon, authenticated;

ALTER TABLE "staff_messages" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "staff_messages" FROM anon, authenticated;

ALTER TABLE "staff_notifications" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "staff_notifications" FROM anon, authenticated;

ALTER TABLE "staff_password_resets" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "staff_password_resets" FROM anon, authenticated;

ALTER TABLE "staff_shift_reminders" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "staff_shift_reminders" FROM anon, authenticated;

ALTER TABLE "staff_shift_visit_notes" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "staff_shift_visit_notes" FROM anon, authenticated;

ALTER TABLE "staff_shifts" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "staff_shifts" FROM anon, authenticated;

ALTER TABLE "staff_training" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "staff_training" FROM anon, authenticated;

ALTER TABLE "subject_requests" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "subject_requests" FROM anon, authenticated;

ALTER TABLE "system_settings" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "system_settings" FROM anon, authenticated;

ALTER TABLE "user_roles" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "user_roles" FROM anon, authenticated;

ALTER TABLE "website_announcements" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "website_announcements" FROM anon, authenticated;

ALTER TABLE "website_jobs" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "website_jobs" FROM anon, authenticated;

REVOKE EXECUTE ON FUNCTION public.datetime(text, VARIADIC text[]) FROM PUBLIC, anon, authenticated;

REVOKE EXECUTE ON FUNCTION public.date(text, VARIADIC text[]) FROM PUBLIC, anon, authenticated;

REVOKE EXECUTE ON FUNCTION public.datetime(text) FROM PUBLIC, anon, authenticated;

REVOKE EXECUTE ON FUNCTION public.date(text) FROM PUBLIC, anon, authenticated;

COMMIT;

