const { Pool } = require("pg");
const { PGlite } = require("@electric-sql/pglite");
const path = require("path");

const databaseUrl = process.env.DATABASE_URL || process.env.SUPABASE_DATABASE_URL || "";
const dbPath = databaseUrl || path.join(__dirname, "..", "database", "everkind.db");

let memoryPool = null;

const toPostgresInterval = (offset) => {
    const rawOffset = String(offset || "").trim();
    if (!rawOffset) return "";
    const match = rawOffset.match(/^([+-])\s*(\d+)\s*(minute|minutes|hour|hours|day|days|week|weeks|month|months|year|years)$/i);
    if (!match) {
        return `INTERVAL '${rawOffset}'`;
    }
    const sign = match[1];
    const amount = Number(match[2]);
    const unit = match[3].toLowerCase();
    return `${sign === "+" ? "+" : "-"} INTERVAL '${amount} ${unit}'`;
};

const ensureSubqueryAliases = (sql = "") => {
    let normalized = String(sql);
    normalized = normalized.replace(/FROM\s+\(([^]*?)\)(?=\s*(?:WHERE|GROUP|ORDER|HAVING|LIMIT|UNION|INTERSECT|EXCEPT|;|$))/gi, (match, subquery) => {
        if (/\)\s+(?:AS\s+)?[A-Za-z_][A-Za-z0-9_]*/i.test(match)) {
            return match;
        }
        return `FROM (${subquery}) AS derived_table`;
    });
    return normalized;
};

const normalizeSqlForPostgres = (sql = "") => {
    let normalized = String(sql).trim();
    if (!normalized) {
        return normalized;
    }

    normalized = ensureSubqueryAliases(normalized);
    normalized = normalized.replace(/\bAUTOINCREMENT\b/gi, "GENERATED BY DEFAULT AS IDENTITY");
    normalized = normalized.replace(/INSERT\s+OR\s+IGNORE\s+INTO/gi, "INSERT INTO");
    normalized = normalized.replace(/INSERT\s+OR\s+REPLACE\s+INTO/gi, "INSERT INTO");
    normalized = normalized.replace(/INSERT\s+INTO\s+([A-Za-z0-9_\."`]+)\s*(\([^)]+\))?\s+VALUES\s+([\s\S]*?)(?=\s*ON\s+CONFLICT|\s*;|\s*$)/gi, (match, tableName, columns, values) => `INSERT INTO ${tableName}${columns || ""} VALUES ${values} ON CONFLICT DO NOTHING`);
    normalized = normalized.replace(/ON CONFLICT DO NOTHING\s+ON CONFLICT/gi, "ON CONFLICT");
    normalized = normalized.replace(/ON CONFLICT\s*\(([^)]+)\)/gi, "ON CONFLICT ($1)");
    normalized = normalized.replace(/INT\s*PRIMARY\s+KEY\s+AUTOINCREMENT/gi, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
    normalized = normalized.replace(/INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
    normalized = normalized.replace(/TEXT\s+DEFAULT\s+CURRENT_TIMESTAMP/gi, "TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP");
    normalized = normalized.replace(/([A-Za-z_][A-Za-z0-9_]*)\.(start|end)\b/gi, '$1."$2"');
    normalized = normalized.replace(/(SET\s+)(start|end)(?=\s*=)/gi, '$1"$2"');
    normalized = normalized.replace(/([,(])\s*(start|end)\s*(?=[,)\s])/gi, '$1"$2"');
    normalized = normalized.replace(/\b(start|end)\s+(?=(?:TEXT|INTEGER|REAL|TIMESTAMPTZ|BOOLEAN|DATE|TIME|NUMERIC|JSON))/gi, '"$1" ');
    normalized = normalized.replace(/printf\(\s*'(%0?)(\d+)d'\s*,\s*([^)]+)\)/gi, (_, pad, width, expression) => `LPAD(CAST(${expression.trim()} AS TEXT), ${Number(width)}, '0')`);
    normalized = normalized.replace(/datetime\(\s*'now'\s*\)/gi, "NOW()");
    normalized = normalized.replace(/date\(\s*'now'\s*\)/gi, "CURRENT_DATE");
    normalized = normalized.replace(/datetime\(\s*'now'\s*,\s*'([^']+)'\s*\)/gi, (_, offset) => `NOW() ${toPostgresInterval(offset)}`);
    normalized = normalized.replace(/date\(\s*'now'\s*,\s*'([^']+)'\s*\)/gi, (_, offset) => `CURRENT_DATE ${toPostgresInterval(offset)}`);
    normalized = normalized.replace(/datetime\(\s*([^,]+?)\s*,\s*'([^']+)'\s*\)/gi, (match, expression, offset) => {
        const expr = expression.trim();
        if (expr === "'now'" || expr === "NOW()") {
            return `NOW() ${toPostgresInterval(offset)}`;
        }
        return `(${expr} + INTERVAL '${offset}')`;
    });
    normalized = normalized.replace(/date\(\s*([^,]+?)\s*,\s*'([^']+)'\s*\)/gi, (match, expression, offset) => {
        const expr = expression.trim();
        if (expr === "'now'" || expr === "NOW()") {
            return `CURRENT_DATE ${toPostgresInterval(offset)}`;
        }
        return `(${expr} + INTERVAL '${offset}')`;
    });
    normalized = normalized.replace(/datetime\(\s*([^)]+?)\s*\)/gi, (_, expression) => `CAST(${expression.trim()} AS TIMESTAMP)`);
    normalized = normalized.replace(/date\(\s*([^)]+?)\s*\)/gi, (_, expression) => `CAST(${expression.trim()} AS DATE)`);
    normalized = normalized.replace(/PRAGMA\s+table_info\(\s*([A-Za-z0-9_]+)\s*\)/gi, (_, tableName) => `SELECT column_name AS "name", ordinal_position AS "cid", data_type AS "type", CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END AS "notnull", column_default AS "dflt_value", CASE WHEN is_identity = 'YES' THEN 1 ELSE 0 END AS "pk" FROM information_schema.columns WHERE table_name = '${tableName}' ORDER BY ordinal_position`);

    return normalized;
};

const ensureMemoryPool = () => {
    if (!memoryPool) {
        memoryPool = new PGlite();
    }
    return memoryPool;
};

const databasePool = databaseUrl
    ? new Pool({
        connectionString: databaseUrl,
        ssl: process.env.PGSSLMODE === "require" || process.env.SUPABASE_SSL === "true"
            ? { rejectUnauthorized: false }
            : undefined,
    })
    : ensureMemoryPool();

const prepareQuery = (sql, params = []) => {
    let normalizedSql = normalizeSqlForPostgres(sql);
    if (/^INSERT\s+INTO\s+/i.test(normalizedSql) && !/\bRETURNING\b/i.test(normalizedSql)) {
        normalizedSql = normalizedSql.replace(/;\s*$/, "");
        normalizedSql = `${normalizedSql} RETURNING *`;
    }
    let placeholderIndex = 0;
    const sqlWithParams = normalizedSql.replace(/\?/g, () => {
        placeholderIndex += 1;
        return `$${placeholderIndex}`;
    });
    return {
        sql: sqlWithParams,
        values: params,
    };
};

const runDb = async (sql, params = []) => {
    const { sql: adaptedSql, values } = prepareQuery(sql, params);
    try {
        const result = await databasePool.query(adaptedSql, values);
        const lastRow = result.rows && result.rows[0] ? result.rows[0] : null;
        return {
            ...result,
            lastID: lastRow && Object.prototype.hasOwnProperty.call(lastRow, "id") ? Number(lastRow.id) : null,
            changes: result.rowCount ?? 0,
        };
    } catch (error) {
        console.error("Postgres query failed:", adaptedSql, values);
        throw error;
    }
};

const getDb = async (sql, params = []) => {
    const { sql: adaptedSql, values } = prepareQuery(sql, params);
    try {
        const result = await databasePool.query(adaptedSql, values);
        return result.rows[0] || null;
    } catch (error) {
        console.error("Postgres query failed:", adaptedSql, values);
        throw error;
    }
};

const allDb = async (sql, params = []) => {
    const { sql: adaptedSql, values } = prepareQuery(sql, params);
    try {
        const result = await databasePool.query(adaptedSql, values);
        return result.rows;
    } catch (error) {
        console.error("Postgres query failed:", adaptedSql, values);
        throw error;
    }
};

const db = databasePool;

module.exports = {
    db,
    dbPath,
    databaseUrl,
    runDb,
    getDb,
    allDb,
    normalizeSqlForPostgres,
    prepareQuery,
};
