-- Everkind Supabase PostgreSQL schema
-- Migrated from the SQLite schema used by server/app.js.

CREATE TABLE IF NOT EXISTS app_status (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    status TEXT NOT NULL DEFAULT 'healthy',
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_settings (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subject_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_type TEXT NOT NULL,
    patient_id INTEGER,
    requested_by TEXT,
    status TEXT NOT NULL,
    details TEXT,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS patients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    date_of_birth TEXT,
    gender TEXT,
    address TEXT,
    phone TEXT,
    email TEXT,
    emergency_contact TEXT,
    care_level TEXT,
    status TEXT DEFAULT 'Active',
    risk_level TEXT DEFAULT 'Low',
    latitude REAL,
    longitude REAL,
    geofence_radius_meters INTEGER DEFAULT 80,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    age INTEGER,
    condition TEXT,
    carePlan TEXT,
    nextVisit TEXT,
    name TEXT,
    legal_basis TEXT DEFAULT 'care_contract',
    consent_status TEXT DEFAULT 'pending',
    consent_recorded_at TIMESTAMPTZ,
    consent_recorded_by TEXT,
    data_retention_until TIMESTAMPTZ,
    is_archived INTEGER DEFAULT 0,
    archived_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS appointments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER,
    staff_id INTEGER,
    title TEXT,
    start TIMESTAMPTZ,
    end TIMESTAMPTZ,
    notes TEXT,
    status TEXT DEFAULT 'Scheduled',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    client TEXT,
    date TEXT,
    time TEXT,
    type TEXT
);

CREATE TABLE IF NOT EXISTS care_notes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER,
    author TEXT,
    note TEXT,
    severity TEXT DEFAULT 'Normal',
    retention_expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS care_reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL,
    review_type TEXT NOT NULL DEFAULT 'care',
    reviewer_staff_id INTEGER,
    due_date TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'upcoming',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    role TEXT,
    email TEXT UNIQUE,
    phone TEXT,
    status TEXT DEFAULT 'Active',
    password_hash TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    name TEXT,
    shift TEXT
);

CREATE TABLE IF NOT EXISTS admin_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE,
    password_hash TEXT,
    role TEXT DEFAULT 'super_admin',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_key TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    description TEXT,
    is_system INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_key TEXT NOT NULL UNIQUE,
    module_key TEXT NOT NULL,
    action TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id INTEGER NOT NULL,
    permission_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_roles (
    admin_user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    scope_type TEXT NOT NULL DEFAULT 'global',
    scope_value TEXT NOT NULL DEFAULT '',
    is_primary INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (admin_user_id, role_id, scope_type, scope_value),
    FOREIGN KEY (admin_user_id) REFERENCES admin_users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS staff_shifts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER,
    patient_id INTEGER,
    shift_date TIMESTAMPTZ,
    scheduled_start TIMESTAMPTZ,
    scheduled_end TIMESTAMPTZ,
    actual_clock_in TIMESTAMPTZ,
    actual_clock_out TIMESTAMPTZ,
    status TEXT DEFAULT 'scheduled',
    clock_in_latitude REAL,
    clock_in_longitude REAL,
    clock_out_latitude REAL,
    clock_out_longitude REAL,
    clock_in_note TEXT,
    clock_out_note TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type TEXT NOT NULL,
    actor_identifier TEXT,
    action TEXT NOT NULL,
    target_type TEXT,
    target_identifier TEXT,
    outcome TEXT NOT NULL,
    reason TEXT,
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff_notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    type TEXT DEFAULT 'info',
    link_url TEXT,
    is_read INTEGER DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL,
    sender_type TEXT NOT NULL,
    sender_name TEXT NOT NULL,
    subject TEXT,
    body TEXT NOT NULL,
    is_read INTEGER DEFAULT 0,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff_documents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    file_name TEXT,
    download_text TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shift_attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    file_name TEXT,
    download_text TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS patient_assignments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL,
    staff_id INTEGER NOT NULL,
    assignment_role TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS patient_documents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    file_name TEXT NOT NULL,
    mime_type TEXT,
    data_url TEXT NOT NULL,
    is_staff_visible INTEGER DEFAULT 1,
    uploaded_by TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff_shift_visit_notes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id INTEGER NOT NULL,
    staff_id INTEGER NOT NULL,
    note TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff_shift_reminders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id INTEGER NOT NULL,
    staff_id INTEGER NOT NULL,
    reminder_type TEXT NOT NULL,
    reminder_minutes INTEGER,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff_training (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    status TEXT DEFAULT 'completed',
    completed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff_password_resets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL,
    code_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS client_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_name TEXT NOT NULL,
    trading_name TEXT,
    organization_type TEXT NOT NULL,
    registration_number TEXT,
    hiqa_registration_number TEXT,
    hse_contract_number TEXT,
    vat_number TEXT,
    website TEXT,
    contact_first_name TEXT NOT NULL,
    contact_last_name TEXT NOT NULL,
    contact_job_title TEXT,
    email TEXT UNIQUE NOT NULL,
    mobile_number TEXT NOT NULL,
    office_telephone TEXT,
    address_line_1 TEXT NOT NULL,
    address_line_2 TEXT,
    town TEXT NOT NULL,
    county TEXT NOT NULL,
    eircode TEXT,
    gps_latitude REAL,
    gps_longitude REAL,
    service_requirements TEXT,
    number_of_beds TEXT,
    number_of_residents TEXT,
    number_of_units TEXT,
    existing_staff_numbers TEXT,
    current_staffing_provider TEXT,
    preferred_shift_types TEXT,
    gdpr_agreement INTEGER DEFAULT 0,
    privacy_agreement INTEGER DEFAULT 0,
    terms_agreement INTEGER DEFAULT 0,
    hiqa_compliance_agreement INTEGER DEFAULT 0,
    authorised_representative INTEGER DEFAULT 0,
    status TEXT DEFAULT 'pending',
    password_hash TEXT,
    portal_login_enabled INTEGER DEFAULT 0,
    portal_login_suspended INTEGER DEFAULT 0,
    portal_login_deactivated INTEGER DEFAULT 0,
    approved_at TIMESTAMPTZ,
    approved_by TEXT,
    review_notes TEXT,
    assigned_account_manager TEXT,
    favourite_staff_ids TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS client_password_resets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_account_id INTEGER NOT NULL,
    code_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS website_announcements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    headline TEXT NOT NULL,
    message TEXT,
    color TEXT DEFAULT 'emerald',
    priority TEXT DEFAULT 'normal',
    enabled INTEGER DEFAULT 1,
    auto_scroll INTEGER DEFAULT 1,
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS website_jobs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    location TEXT,
    county TEXT,
    employment_type TEXT,
    salary TEXT,
    description TEXT,
    requirements TEXT,
    benefits TEXT,
    closing_date TIMESTAMPTZ,
    featured INTEGER DEFAULT 0,
    urgent INTEGER DEFAULT 0,
    published INTEGER DEFAULT 1,
    archived INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mfa_challenges (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_type TEXT NOT NULL,
    account_id INTEGER NOT NULL,
    purpose TEXT NOT NULL,
    method TEXT NOT NULL,
    nonce TEXT NOT NULL,
    code_hash TEXT NOT NULL,
    attempts_remaining INTEGER NOT NULL DEFAULT 5,
    expires_at TIMESTAMPTZ NOT NULL,
    resend_after TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mfa_recovery_codes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_type TEXT NOT NULL,
    account_id INTEGER NOT NULL,
    code_hash TEXT NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS password_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_type TEXT NOT NULL,
    account_id INTEGER NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS client_service_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_account_id INTEGER NOT NULL,
    staff_required TEXT NOT NULL,
    quantity_required INTEGER DEFAULT 1,
    shift_type TEXT NOT NULL,
    shift_date TIMESTAMPTZ NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    ward_unit TEXT,
    resident_identifier TEXT,
    room_number TEXT,
    resident_unit TEXT,
    required_skills TEXT,
    notes TEXT,
    priority TEXT DEFAULT 'Routine',
    status TEXT DEFAULT 'open',
    assigned_staff_id INTEGER,
    published_open_shift_id INTEGER,
    scheduled_shift_id INTEGER,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS client_notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_account_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    type TEXT DEFAULT 'info',
    link_url TEXT,
    is_read INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS applications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    role TEXT,
    availability TEXT,
    status TEXT DEFAULT 'new',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS application_timeline (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INTEGER NOT NULL,
    stage TEXT NOT NULL,
    title TEXT NOT NULL,
    notes TEXT,
    actor_type TEXT,
    actor_identifier TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payroll_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    total_hours REAL DEFAULT 0,
    gross_pay REAL DEFAULT 0,
    net_pay REAL DEFAULT 0,
    mileage_km REAL DEFAULT 0,
    mileage_payment REAL DEFAULT 0,
    status TEXT DEFAULT 'draft',
    approved_by TEXT,
    approved_at TIMESTAMPTZ,
    paid_at TIMESTAMPTZ,
    payment_date TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(staff_id, period_start, period_end)
);

CREATE TABLE IF NOT EXISTS payslips (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL,
    payroll_record_id INTEGER,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    gross_pay REAL DEFAULT 0,
    net_pay REAL DEFAULT 0,
    file_path TEXT,
    payment_date TIMESTAMPTZ,
    email_status TEXT DEFAULT 'not_scheduled',
    email_scheduled_at TIMESTAMPTZ,
    email_sent_at TIMESTAMPTZ,
    generated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    generated_by TEXT,
    payslip_ref TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS payslip_email_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payslip_id INTEGER,
    recipient TEXT,
    status TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_mfa_challenges_account ON mfa_challenges(account_type, account_id, purpose, created_at);
CREATE INDEX IF NOT EXISTS idx_mfa_recovery_account ON mfa_recovery_codes(account_type, account_id, used_at);
CREATE INDEX IF NOT EXISTS idx_password_history_account ON password_history(account_type, account_id, created_at);
CREATE INDEX IF NOT EXISTS idx_admin_users_active ON admin_users(username);
CREATE INDEX IF NOT EXISTS idx_user_roles_admin_user ON user_roles(admin_user_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_actor_role ON audit_events(actor_type, actor_identifier);
